2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Configure stats pid to 3969462
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Loading settings from /home/onebom/.config/wandb/settings
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Loading settings from /data/onebom/project/ongoing/point_based_vp/prediction/wandb/settings
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'prediction/train.py', 'program_abspath': '/data/onebom/project/ongoing/point_based_vp/prediction/train.py', 'program': '/data/onebom/project/ongoing/point_based_vp/prediction/train.py'}
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_init.py:_log_setup():534] Logging user logs to /data/onebom/project/ongoing/point_based_vp/prediction/wandb/run-20250121_161658-hdg5awt4/logs/debug.log
2025-01-21 16:16:58,178 INFO    MainThread:3969462 [wandb_init.py:_log_setup():535] Logging internal logs to /data/onebom/project/ongoing/point_based_vp/prediction/wandb/run-20250121_161658-hdg5awt4/logs/debug-internal.log
2025-01-21 16:16:58,179 INFO    MainThread:3969462 [wandb_init.py:init():621] calling init triggers
2025-01-21 16:16:58,179 INFO    MainThread:3969462 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {}
2025-01-21 16:16:58,179 INFO    MainThread:3969462 [wandb_init.py:init():666] wandb.init() called when a run is still active
2025-01-21 16:20:09,600 WARNING MsgRouterThr:3969462 [router.py:message_loop():77] message_loop has been closed
